In [1]:
import pandas as pd
file = 'SCDB_2021_01_caseCentered_Docket.dta'
df = pd.read_stata(file, convert_categoricals = False)
df.head()

,caseId,docketId,caseIssuesId,voteId,dateDecision,decisionType,usCite,sctCite,ledCite,lexisCite,...,authorityDecision1,authorityDecision2,lawType,lawSupp,lawMinor,majOpinWriter,majOpinAssigner,splitVote,majVotes,minVotes
0,1946-001,1946-001-01,1946-001-01-01,1946-001-01-01-01,1946-11-18,1,329 U.S. 1,67 S. Ct. 6,91 L. Ed. 3,1946 U.S. LEXIS 1724,...,4.0,NaN,6.0,600.0,35 U.S.C. § 33,78.0,78.0,1,8,1
1,1946-002,1946-002-01,1946-002-01-01,1946-002-01-01-01,1946-11-18,1,329 U.S. 14,67 S. Ct. 13,91 L. Ed. 12,1946 U.S. LEXIS 1725,...,4.0,NaN,6.0,600.0,18 U.S.C. § 398,81.0,87.0,1,6,3
2,1946-002,1946-002-02,1946-002-02-01,1946-002-02-01-01,1946-11-18,1,329 U.S. 14,67 S. Ct. 13,91 L. Ed. 12,1946 U.S. LEXIS 1725,...,4.0,NaN,6.0,600.0,18 U.S.C. § 398,81.0,87.0,1,6,3
3,1946-002,1946-002-03,1946-002-03-01,1946-002-03-01-01,1946-11-18,1,329 U.S. 14,67 S. Ct. 13,91 L. Ed. 12,1946 U.S. LEXIS 1725,...,4.0,NaN,6.0,600.0,18 U.S.C. § 398,81.0,87.0,1,6,3
4,1946-002,1946-002-04,1946-002-04-01,1946-002-04-01-01,1946-11-18,1,329 U.S. 14,67 S. Ct. 13,91 L. Ed. 12,1946 U.S. LEXIS 1725,...,4.0,NaN,6.0,600.0,18 U.S.C. § 398,81.0,87.0,1,6,3

In [2]:
#assign year and month using datetime (dt)
date_col = 'dateDecision'
df['year'] = df[date_col].dt.year
df['month'] = df[date_col].dt.month
df[[date_col,'year','month']].head()

  dateDecision  year  month
0   1946-11-18  1946     11
1   1946-11-18  1946     11
2   1946-11-18  1946     11
3   1946-11-18  1946     11
4   1946-11-18  1946     11

In [ ]:
#assign year using string slice
date_col = 'caseId'
df['year'] = df[date_col].str[:4]
df[[date_col,'year']].head()

In [3]:
#df['year'] = pd.to_numeric(df['year']) #<-convert to numeric IF string datatype
after_50_df = df[df['year'] >= 1950]
after_50_before_70_df = after_50_df[after_50_df['year']<1970]
min_year = after_50_before_70_df['year'].min()
max_year = after_50_before_70_df['year'].max()
print(min_year, max_year)

1950 1969